name: s1swot
channels:
    - conda-forge
# channel_priority tells mamba to strictly prefer packages from higher-priority
# channels (in this case, the only channel is conda-forge).
channel_priority: strict
dependencies:
    - python=3.12
    - numpy
    - pandas
    - xarray
    - antimeridian
    - shapely
    - tqdm
    - geopandas
    - geodatasets
    - cdsodatacli
    - h5netcdf
    - netcdf4
    - paramiko
    - alphashape
