name: s1swotcolocs-tests
channels:
    - conda-forge
dependencies:
    - ipython
    - python
    - pre-commit
    - pytest
    - pytest-reportlog
    - pytest-cov
    - numpy
    - toolz
    - cytoolz
    - python-dateutil
    - construct
    - fsspec
    - xarray
    - aiohttp
    - pyproj
    - scipy
    - shapely
    - geopandas
    - antimeridian
    - tqdm
    - pandas
    - geodatasets
    - cdsodatacli
    - h5netcdf
    - alphashape
    - geoviews
    - hvplot
    - netcdf4
    - pystac
    - pystac-client
